definitions:
  req.CallbackClaimCompleteReq:
    properties:
      claimTotalAmount:
        description: 理赔总金额
        type: number
      payeeList:
        items:
          $ref: '#/definitions/req.Payee'
        type: array
      policyNo:
        type: string
    type: object
  req.CallbackClaimReplenishReq:
    properties:
      claimTotalAmount:
        description: 理赔总金额
        type: number
      fileName:
        description: 需要用户补传的文件名称。
        type: string
      policyNo:
        type: string
    type: object
  req.CallbackInvoiceReq:
    properties:
      downLoadUrl:
        description: 电子发票下下载地址
        type: string
      policyNo:
        description: 保单号
        type: string
    type: object
  req.CallbackSurrendReq:
    properties:
      policyNo:
        description: 保单号
        type: string
      resultFlag:
        description: true 成功 false 失败
        type: string
      resultMessage:
        description: 处理结果
        type: string
    type: object
  req.Payee:
    properties:
      claimAccountBankName:
        description: 收款开户银行名称
        type: string
      claimAccountNo:
        description: 收款人账号
        type: string
      claimAccountUser:
        description: 收款人名称
        type: string
      claimAmount:
        description: 赔付金额
        type: number
    type: object
  result.Page:
    properties:
      count:
        type: integer
      index:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  result.Result:
    properties:
      data: {}
      msg:
        type: string
      page:
        $ref: '#/definitions/result.Page'
      status:
        type: integer
    type: object
info:
  contact: {}
  description: 鼎函太保对接系统
  title: 鼎函太保对接系统
  version: 1.0.0(bid-dinghan-cpic)
paths:
  /callback/account/query:
    get:
      consumes:
      - application/json
      parameters:
      - description: 查询日期
        in: query
        name: queryDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询对账明细
      tags:
      - 对账
  /callback/claim/notice:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/req.CallbackClaimCompleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/result.Result'
      summary: 理赔成功回执
      tags:
      - 回执
  /callback/claim/replenish:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/req.CallbackClaimReplenishReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/result.Result'
      summary: 理赔补充文件回执
      tags:
      - 回执
  /callback/invoice:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.CallbackInvoiceReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/result.Result'
      summary: 发票回执
      tags:
      - 回执
  /callback/surrend:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/req.CallbackSurrendReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/result.Result'
      summary: 退保回执
      tags:
      - 回执
swagger: "2.0"
